# Getting-and-Cleaning-Data-Project
Course project for getting and cleaning data coursera course
## Part 1 code
The first section of code downloads the required documents from the url. An if 
statement is included so that files do not get redownloaded if they are already
present. The Train dataset is with the 571 feature vector is combined with the
participant ID and the physical activity identifier. This dataframe is organized
with participant ID in the first column, the physical activity identifier in the
second column, and the feature vector in the subsequent columns. The same was
done for the Test dataset. These were then combined using rbind to make one large
dataset with data from all the participants.

## Part 2 code
The next section reads in the features.txt file which has all of the variable
names for the gyroscope and accelerometer data. Using the grepl function, a logical
vector of names that contain either mean or std is created. Using this, the 
combined data from the previous step is filtered to only contain features in 
accordance with the logical vector. This trimmed data is then joined with the 
participant ID column and physical activity column

## Part 3 code
The activity_labels.txt file is read in and is used to replace the numeric 
representations for physical activities with strings. Underscores were removed 
from the strings to eliminate an downstream errors caused by including non 
alphanumeric characters.

## Part 4 code
